# Generated by Django 4.2.27 on 2026-03-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="highlights",
            field=models.TextField(blank=True, null=True),
        ),
    ]
