# Generated by Django 4.2.27 on 2026-03-03 09:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_review_reviewimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="r_image"
            ),
        ),
    ]
