# Generated by Django 4.2.27 on 2026-03-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_reviewimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="discount_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
