# Generated by Django 4.2.27 on 2026-04-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_brand_product_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="logo",
        ),
    ]
