# Generated by Django 4.2.27 on 2026-04-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_order_order_id_orderitem_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PACKED", "Packed"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURNED", "Returned"),
                    ("REFUNDED", "Refunded"),
                    ("PARTIAL_CANCELLED", "Partial Cancelled"),
                    ("PARTIAL_RETURNED", "Partial Returned"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
