# Generated by Django 4.2.27 on 2026-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_order_order_id_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash On Delivery"), ("RAZORPAY", "Razorpay")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
