# Generated by Django 4.2.27 on 2026-07-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_orderaddress_remove_order_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="discount_percentage",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="discount_price",
        ),
    ]
