# Generated by Django 4.2.27 on 2026-07-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_remove_productvariant_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="referral_rewarded",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
