# Generated by Django 4.2.27 on 2026-07-10 09:56

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_order_referral_rewarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                max_length=500, validators=[apps.core.validators.validate_description]
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[apps.core.validators.validate_name],
            ),
        ),
    ]
