# Generated by Django 4.2.27 on 2026-07-10 11:48

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_alter_category_description_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="highlights",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                validators=[apps.core.validators.validate_description]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=200, validators=[apps.core.validators.validate_name]
            ),
        ),
    ]
