# Generated by Django 4.2.27 on 2026-07-10 12:02

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0023_remove_product_highlights_alter_product_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=500,
                validators=[apps.core.validators.validate_description],
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[apps.core.validators.validate_name],
            ),
        ),
    ]
