# Generated by Django 4.2.27 on 2026-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_alter_brand_description_alter_brand_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PACKED", "Packed"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("PARTIAL_CANCELLED", "Partial Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURNED", "Returned"),
                    ("PARTIAL_RETURNED", "Partial Returned"),
                    ("REFUNDED", "Refunded"),
                    ("PARTIAL_REFUNDED", "Partial Refunded"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
