# Generated by Django 4.2.27 on 2026-08-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_productvariant_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('RAZORPAY', 'Razorpay'), ('ONLINE', 'Online Payment'), ('WALLET', 'Wallet')], default='COD', max_length=20),
        ),
    ]
