# Generated by Django 4.2.27 on 2026-07-12 16:48

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryoffer",
            name="name",
            field=models.CharField(
                max_length=100, validators=[apps.core.validators.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="productoffer",
            name="name",
            field=models.CharField(
                max_length=100, validators=[apps.core.validators.validate_name]
            ),
        ),
    ]
