# Generated by Django 4.2.27 on 2026-07-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="usage_limit",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="used_count",
        ),
    ]
