# Generated by Django 4.2.27 on 2026-08-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_remove_coupon_usage_limit_remove_coupon_used_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="coupon",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
