# Generated by Django 4.2.27 on 2026-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="gateway_order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="gateway_payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="gateway_signature",
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_signature",
            field=models.TextField(blank=True, null=True),
        ),
    ]
