# Generated by Django 4.2.27 on 2025-12-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_emailotp_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailOTP",
        ),
    ]
