# Generated by Django 4.2.27 on 2026-01-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
