# Generated by Django 4.2.27 on 2026-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_reward_granted",
            field=models.BooleanField(default=False),
        ),
    ]
