# Generated by Django 4.2.27 on 2026-07-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_referral_reward_granted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="referral_reward_granted",
        ),
    ]
