# Generated by Django 4.2.27 on 2026-07-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_user_referral_reward_granted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
