# Generated by Django 4.2.27 on 2026-07-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_reward_granted",
            field=models.BooleanField(default=False),
        ),
    ]
