# Generated by Django 4.2.27 on 2026-07-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_referral_reward_granted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="wallet_balance",
        ),
    ]
